steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/jgn-dev-repo/jgn-dev:$COMMIT_SHA',
    '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/jgn-dev-repo/jgn-dev:latest',
    '.'
  ]

# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push', 
    'us-central1-docker.pkg.dev/$PROJECT_ID/jgn-dev-repo/jgn-dev:$COMMIT_SHA'
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push', 
    'us-central1-docker.pkg.dev/$PROJECT_ID/jgn-dev-repo/jgn-dev:latest'
  ]

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', 'jgn-dev',
    '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/jgn-dev-repo/jgn-dev:$COMMIT_SHA',
    '--region', 'us-central1',
    '--allow-unauthenticated',
    '--set-env-vars', 'GITHUB_TOKEN=$$GITHUB_TOKEN,GITHUB_WEBHOOK_SECRET=$$GITHUB_WEBHOOK_SECRET',
    '--cpu', '1',
    '--memory', '512Mi',
    '--min-instances', '0',
    '--max-instances', '10'
  ]
  secretEnv: ['GITHUB_TOKEN', 'GITHUB_WEBHOOK_SECRET']

# Verify deployment
- name: 'gcr.io/cloud-builders/curl'
  args: ['https://jgn.dev/']

options:
  logging: CLOUD_LOGGING_ONLY

# Configure secrets for environment variables
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/github-token/versions/latest
    env: 'GITHUB_TOKEN'
  - versionName: projects/$PROJECT_ID/secrets/github-webhook-secret/versions/latest
    env: 'GITHUB_WEBHOOK_SECRET'

# Build timeout
timeout: '600s' 