steps:
  # Install Go dependencies
  - name: 'gcr.io/cloud-builders/go'
    args: ['mod', 'download']
    env: ['GO111MODULE=on']

  # Install templ CLI
  - name: 'gcr.io/cloud-builders/go'
    args: ['install', 'github.com/a-h/templ/cmd/templ@latest']
    env: ['GO111MODULE=on']

  # Install Node.js dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci']

  # Generate templ files
  - name: 'gcr.io/cloud-builders/go'
    args: ['run', 'github.com/a-h/templ/cmd/templ@latest', 'generate']
    env: ['GO111MODULE=on']

  # Build CSS with Tailwind
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build:css']

  # Run tests
  - name: 'gcr.io/cloud-builders/go'
    args: ['test', '-v', './...']
    env: ['GO111MODULE=on']

  # Run linting
  - name: 'gcr.io/cloud-builders/go'
    args: ['vet', './...']
    env: ['GO111MODULE=on']

  # Build Docker image with tags
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'
      - '.'

  # Push the container image with SHA tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'

  # Push the container image with latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GITHUB_TOKEN=${_GITHUB_TOKEN},GITHUB_WEBHOOK_SECRET=${_GITHUB_WEBHOOK_SECRET},PORT=8080,GIN_MODE=release'

  # Health check
  - name: 'gcr.io/cloud-builders/curl'
    args:
      - '-f'
      - '--retry'
      - '3'
      - '--retry-delay'
      - '10'
      - 'https://${_SERVICE_NAME}-${_REGION}.a.run.app/'

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Substitutions (variables)
substitutions:
  _GAR_LOCATION: 'us-central1'
  _REPOSITORY: 'jgn-dev-repo'
  _SERVICE_NAME: 'jgn-dev'
  _REGION: 'us-central1'
  _GITHUB_TOKEN: '${_GITHUB_TOKEN}'
  _GITHUB_WEBHOOK_SECRET: '${_GITHUB_WEBHOOK_SECRET}' 