name: Build and Push to GCR

on:
  push:
    branches: [ main ]

env:
  GCR_REGION: us # or your preferred GCR region
  IMAGE: jgn-website

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: gcloud auth configure-docker ${{ env.GCR_REGION }}-docker.pkg.dev

    - name: Build Docker image
      run: docker build -t ${{ env.GCR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.IMAGE }}:${{ github.sha }} .

    - name: Push Docker image to GCR
      run: docker push ${{ env.GCR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.IMAGE }}:${{ github.sha }}

    - name: Push Docker image with latest tag
      run: |
        docker tag ${{ env.GCR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.IMAGE }}:${{ github.sha }} ${{ env.GCR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.IMAGE }}:latest
        docker push ${{ env.GCR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.IMAGE }}:latest
